In [103]:
import numpy as np

In [115]:
import pandas as pd

In [116]:
np.random.seed(0)

### Problem 4.2 Code

#### Generate 3 Matrices

In [117]:
matrix1 = np.random.randint(-10, 11, size = (3,3))
print(matrix1)

[[  2   5 -10]
 [ -7  -7  -3]
 [ -1   9   8]]


In [118]:
matrix2 = np.random.randint(-10, 11, size = (3,3))
print(matrix2)

[[-6 -4  2]
 [-9 -4 -3]
 [ 4  7 -5]]


In [119]:
matrix3 = np.random.randint(-10, 11, size = (3,3))
print(matrix3)

[[ 3 -2 -1]
 [10  9  6]
 [ 9 -5  5]]


#### Compute Inverses

In [165]:
matrix1Inv = np.linalg.inv(matrix1)
print(matrix1Inv)

[[-0.03094984 -0.13874066 -0.09071505]
 [ 0.06296692  0.00640342  0.08110993]
 [-0.07470651 -0.02454642  0.02241195]]


In [166]:
matrix2Inv = np.linalg.inv(matrix2)
print(matrix2Inv)

[[-0.36607143  0.05357143 -0.17857143]
 [ 0.50892857 -0.19642857  0.32142857]
 [ 0.41964286 -0.23214286  0.10714286]]


In [167]:
matrix3Inv = np.linalg.inv(matrix3)
print(matrix3Inv)

[[ 0.21551724  0.04310345 -0.00862069]
 [ 0.01149425  0.06896552 -0.08045977]
 [-0.37643678 -0.00862069  0.13505747]]


#### Identity Matrices

In [123]:
matrix1 @ matrix1Inv

array([[ 1.00000000e+00,  3.46944695e-17,  3.46944695e-17],
       [-2.77555756e-17,  1.00000000e+00, -1.42247325e-16],
       [ 1.11022302e-16,  1.38777878e-17,  1.00000000e+00]])

In [124]:
matrix2 @ matrix2Inv

array([[ 1.00000000e+00,  5.55111512e-17, -8.32667268e-17],
       [-2.77555756e-16,  1.00000000e+00, -9.71445147e-17],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [125]:
matrix3 @ matrix3Inv

array([[ 1.00000000e+00,  3.46944695e-18, -2.77555756e-17],
       [-3.33066907e-16,  1.00000000e+00,  0.00000000e+00],
       [-2.98372438e-16,  5.55111512e-17,  1.00000000e+00]])

## Problem 5 Code

#### Initial Setup of Data

In [127]:
df = pd.read_csv("kc_house_data.csv")

In [128]:
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [137]:
featuresOnly = df.drop(columns=["id", "date", "zipcode", "price"])
featuresOnly.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0         3       1.00         1180      5650     1.0           0     0   
1         3       2.25         2570      7242     2.0           0     0   
2         2       1.00          770     10000     1.0           0     0   
3         4       3.00         1960      5000     1.0           0     0   
4         3       2.00         1680      8080     1.0           0     0   

   condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0          3      7        1180              0      1955             0   
1          3      7        2170            400      1951          1991   
2          3      6         770              0      1933             0   
3          5      7        1050            910      1965             0   
4          3      8        1680              0      1987             0   

       lat     long  sqft_living15  sqft_lot15  
0  47.5112 -122.257           1340        5650  
1  47.7210 -122.319           1690        7639  
2  47.7379 -122.233           2720        8062  
3  47.5208 -122.393           1360        5000  
4  47.6168 -122.045           1800        7503

#### 5.1

In [156]:
means = featuresOnly.mean()
means.sort_values()

long              -122.213896
waterfront           0.007542
view                 0.234303
floors               1.494309
bathrooms            2.114757
bedrooms             3.370842
condition            3.409430
grade                7.656873
lat                 47.560053
yr_renovated        84.402258
sqft_basement      291.509045
sqft_above        1788.390691
yr_built          1971.005136
sqft_living15     1986.552492
sqft_living       2079.899736
sqft_lot15       12768.455652
sqft_lot         15106.967566
dtype: float64

In [157]:
mins = featuresOnly.min()
mins.sort_values()

long             -122.5190
bedrooms            0.0000
bathrooms           0.0000
yr_renovated        0.0000
sqft_basement       0.0000
waterfront          0.0000
view                0.0000
grade               1.0000
floors              1.0000
condition           1.0000
lat                47.1559
sqft_above        290.0000
sqft_living       290.0000
sqft_living15     399.0000
sqft_lot          520.0000
sqft_lot15        651.0000
yr_built         1900.0000
dtype: float64

In [158]:
maxes = featuresOnly.max()
maxes.sort_values()

long            -1.213150e+02
waterfront       1.000000e+00
floors           3.500000e+00
view             4.000000e+00
condition        5.000000e+00
bathrooms        8.000000e+00
grade            1.300000e+01
bedrooms         3.300000e+01
lat              4.777760e+01
yr_built         2.015000e+03
yr_renovated     2.015000e+03
sqft_basement    4.820000e+03
sqft_living15    6.210000e+03
sqft_above       9.410000e+03
sqft_living      1.354000e+04
sqft_lot15       8.712000e+05
sqft_lot         1.651359e+06
dtype: float64

In [159]:
variance = featuresOnly.var()
variance.sort_values()

waterfront       7.485226e-03
lat              1.919990e-02
long             1.983262e-02
floors           2.915880e-01
condition        4.234665e-01
view             5.872426e-01
bathrooms        5.931513e-01
bedrooms         8.650150e-01
grade            1.381703e+00
yr_built         8.627973e+02
yr_renovated     1.613462e+05
sqft_basement    1.958727e+05
sqft_living15    4.697612e+05
sqft_above       6.857347e+05
sqft_living      8.435337e+05
sqft_lot15       7.455182e+08
sqft_lot         1.715659e+09
dtype: float64

 #### 5.2 

In [160]:
corr = featuresOnly.corrwith(df["price"])
corr.sort_values()

long             0.021626
condition        0.036362
yr_built         0.054012
sqft_lot15       0.082447
sqft_lot         0.089661
yr_renovated     0.126434
floors           0.256794
waterfront       0.266369
lat              0.307003
bedrooms         0.308350
sqft_basement    0.323816
view             0.397293
bathrooms        0.525138
sqft_living15    0.585379
sqft_above       0.605567
grade            0.667434
sqft_living      0.702035
dtype: float64

In [ ]:
corr_table = corr.to_frame(name="Correlation with Price")
corr_table.sort_values(by="Correlation with Price", ascending=True)

Correlation with Price
long                         0.021626
condition                    0.036362
yr_built                     0.054012
sqft_lot15                   0.082447
sqft_lot                     0.089661
yr_renovated                 0.126434
floors                       0.256794
waterfront                   0.266369
lat                          0.307003
bedrooms                     0.308350
sqft_basement                0.323816
view                         0.397293
bathrooms                    0.525138
sqft_living15                0.585379
sqft_above                   0.605567
grade                        0.667434
sqft_living                  0.702035